import 'package:flutter/material.dart';

class ProductExample {
  final String quality;
  final String catalogue;
  final String categorie;
  final String subcategorie;
  final String code;
  final List codeIndex;
  final String design;
  final String line;
  final String brand;
  final DateTime modified;
  final String name;
  final String size;
  bool? promotion;
  int? promotionDiscount;
  final String imageUrl;

  ProductExample({
    required this.quality,
    required this.catalogue,
    required this.categorie,
    required this.subcategorie,
    required this.code,
    required this.codeIndex,
    required this.design,
    required this.line,
    required this.brand,
    required this.modified,
    required this.name,
    required this.size,
    this.promotion,
    this.promotionDiscount,
    required this.imageUrl,
  });
}

final allProducts = [
  ProductExample(
    quality: '1RA',
    catalogue: 'SET DE DORMITORIO MZ BURGGARTEN',
    categorie: 'ALMOHADA',
    subcategorie: 'DORMITORIO',
    code: '1AC1K002',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0002",
    ],
    design: 'CATACUMBO',
    line: 'ELITE',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 18, 22, 46, 52),
    name: 'Almohada Class King NAC.NIEVE FIRME',
    promotion: false,
    size: 'GRANDE',
    imageUrl:
        'https://cdn.shopify.com/s/files/1/0471/8880/3752/products/AlmohadasKing_JB_1200_800x800.jpg?v=1616699856',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE DORMITORIO MZ EIGHTYSIX',
    categorie: 'COLCHON',
    subcategorie: 'DORMITORIO',
    code: '1AC1K003',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0003",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 10, 22, 46, 52),
    name: 'Colchon Class King NAC.NIEVE FIRME',
    promotion: true,
    promotionDiscount: 10,
    size: 'GRANDE',
    imageUrl:
        'https://colchonescr.com/205-large_default/colchon-queen-nova-gold-jiron.jpg',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE DORMITORIO MZ EIGHTYSIX',
    categorie: 'COLCHON',
    subcategorie: 'DORMITORIO',
    code: '1AC1K003',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0003",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 10, 22, 46, 52),
    name: 'Colchon Class King NAC.NIEVE FIRME',
    promotion: true,
    promotionDiscount: 10,
    size: 'GRANDE',
    imageUrl:
        'https://colchonescr.com/205-large_default/colchon-queen-nova-gold-jiron.jpg',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE DORMITORIO MZ EIGHTYSIX',
    categorie: 'COLCHON',
    subcategorie: 'DORMITORIO',
    code: '1AC1K003',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0003",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 10, 22, 46, 52),
    name: 'Colchon Class King NAC.NIEVE FIRME',
    promotion: true,
    promotionDiscount: 10,
    size: 'GRANDE',
    imageUrl:
        'https://colchonescr.com/205-large_default/colchon-queen-nova-gold-jiron.jpg',
  ),
  ProductExample(
    quality: '1RA',
    catalogue: 'SET DE COCINA MZ BURGGARTEN',
    categorie: 'UTENCILIOS',
    subcategorie: 'COCINA',
    code: '1AC1K004',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0004",
    ],
    design: 'CATACUMBO',
    line: 'ELITE',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 10, 22, 46, 52),
    name: 'Utencilios Class King NAC.NIEVE FIRME',
    promotion: false,
    size: 'MEDIANO',
    imageUrl:
        'https://cdn.shopify.com/s/files/1/0109/6581/1266/products/17_800x.jpg?v=1574791852',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE DORMITORIO MZ BURGGARTEN',
    categorie: 'SABANAS',
    subcategorie: 'DORMITORIO',
    code: '1AC1K005',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0005",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 25, 22, 46, 52),
    name: 'Sabanas Class King NAC.NIEVE FIRME',
    promotion: true,
    promotionDiscount: 20,
    size: 'MEDIANO',
    imageUrl:
        'https://spineto.com.ve/wp/wp-content/uploads/2019/12/766195314697.jpg',
  ),
  ProductExample(
    quality: '1RA',
    catalogue: 'SET DE DORMITORIO MZ BINDER',
    categorie: 'ALMOHADA',
    subcategorie: 'DORMITORIO',
    code: '1AC1K006',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0006",
    ],
    design: 'CATACUMBO',
    line: 'ELITE',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 2, 22, 46, 52),
    name: 'Almohada Class FLUF NAC.NIEVE FIRME',
    promotion: false,
    size: 'MEDIANO',
    imageUrl:
        'https://modopolvos.com/wp-content/uploads/2021/04/Almohada-de-espuma-viscoel-stica-para-parejas-almohada-para-brazo-de-rebote-lento-para-dormir-sin.jpg_Q96-800x800.jpg',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE REPARACION MZ BURGGARTEN',
    categorie: 'HERRAMIENTAS',
    subcategorie: 'REPARACION',
    code: '1AC1K007',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0007",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2022, 8, 20, 22, 46, 52),
    name: 'Herramientas Class King NAC.NIEVE FULL SET',
    promotion: true,
    promotionDiscount: 5,
    size: 'GRANDE',
    imageUrl:
        'https://www.tecnologiaalvarado.com.ve/1081-thickbox_default/kit-de-herramientas-de-red.jpg',
  ),
  ProductExample(
    quality: '1RA',
    catalogue: 'SET DE DORMITORIO NIÑO MZ BURGGARTEN',
    categorie: 'ALMOHADA',
    subcategorie: 'DORMITORIO NIÑO',
    code: '1AC1K008',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0008",
    ],
    design: 'CATACUMBO',
    line: 'ELITE',
    brand: 'Ama de casa',
    modified: DateTime.utc(2020, 8, 18, 22, 46, 52),
    name: 'Almohada Class King NAC.NIEVE FIRME',
    promotion: false,
    size: 'PEQUEÑA',
    imageUrl:
        'https://ae01.alicdn.com/kf/H0b79998235ba4ca0aa32e01128955124Z/Almohada-de-felpa-suave-para-ni-os-y-ni-as-coj-n-de-sof-serie-divertida.jpg_Q90.jpg_.webp',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE BAÑO MZ BURGGARTEN',
    categorie: 'BATAS',
    subcategorie: 'BAÑO',
    code: '1AC1K009',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0009",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2021, 8, 18, 22, 46, 52),
    name: 'BATA DE BAÑO Class King NAC.NIEVE',
    promotion: true,
    promotionDiscount: 50,
    size: 'GRANDE',
    imageUrl:
        'https://ae01.alicdn.com/kf/H5927ea2a7c074984a8f9d9601d3e00e0t/Bata-de-ba-o-rosa-para-hombre-y-mujer-ropa-de-dormir-Sexy-secci-n-delgada.jpg_Q90.jpg_.webp',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE BAÑO MZ BURGGARTEN',
    categorie: 'TOALLA',
    subcategorie: 'BAÑO',
    code: '1AC1K009',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0009",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2021, 8, 18, 22, 46, 52),
    name: 'BATA DE BAÑO Class King NAC.NIEVE',
    promotion: true,
    promotionDiscount: 50,
    size: 'GRANDE',
    imageUrl:
        'https://ae01.alicdn.com/kf/H5927ea2a7c074984a8f9d9601d3e00e0t/Bata-de-ba-o-rosa-para-hombre-y-mujer-ropa-de-dormir-Sexy-secci-n-delgada.jpg_Q90.jpg_.webp',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE BAÑO MZ BURGGARTEN',
    categorie: 'TOALLA',
    subcategorie: 'BAÑO',
    code: '1AC1K009',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0009",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2021, 8, 18, 22, 46, 52),
    name: 'BATA DE BAÑO Class King NAC.NIEVE',
    promotion: true,
    promotionDiscount: 50,
    size: 'GRANDE',
    imageUrl:
        'https://ae01.alicdn.com/kf/H5927ea2a7c074984a8f9d9601d3e00e0t/Bata-de-ba-o-rosa-para-hombre-y-mujer-ropa-de-dormir-Sexy-secci-n-delgada.jpg_Q90.jpg_.webp',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE BAÑO MZ BURGGARTEN',
    categorie: 'TOALLA',
    subcategorie: 'BAÑO',
    code: '1AC1K009',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0009",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2021, 8, 18, 22, 46, 52),
    name: 'BATA DE BAÑO Class King NAC.NIEVE',
    promotion: true,
    promotionDiscount: 50,
    size: 'GRANDE',
    imageUrl:
        'https://ae01.alicdn.com/kf/H5927ea2a7c074984a8f9d9601d3e00e0t/Bata-de-ba-o-rosa-para-hombre-y-mujer-ropa-de-dormir-Sexy-secci-n-delgada.jpg_Q90.jpg_.webp',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE BAÑO MZ BURGGARTEN',
    categorie: 'LENTES',
    subcategorie: 'BAÑO',
    code: '1AC1K009',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0009",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2021, 8, 18, 22, 46, 52),
    name: 'BATA DE BAÑO Class King NAC.NIEVE',
    promotion: true,
    promotionDiscount: 50,
    size: 'GRANDE',
    imageUrl:
        'https://ae01.alicdn.com/kf/H5927ea2a7c074984a8f9d9601d3e00e0t/Bata-de-ba-o-rosa-para-hombre-y-mujer-ropa-de-dormir-Sexy-secci-n-delgada.jpg_Q90.jpg_.webp',
  ),
  ProductExample(
    quality: '2DA',
    catalogue: 'SET DE PLAYA MZ BURGGARTEN',
    categorie: 'LENTES',
    subcategorie: 'BAÑO',
    code: '1AC1K010',
    codeIndex: [
      "1a",
      "1ac",
      "1ac1",
      "1ac1k",
      "1ac1k0",
      "1ac1k00",
      "1ac1k000",
      "1ac1k0010",
    ],
    design: 'LOMO',
    line: 'PROMO',
    brand: 'Ama de casa',
    modified: DateTime.utc(2021, 8, 18, 22, 46, 52),
    name: 'BATA DE PLAYA Class King NAC.NIEVE',
    promotion: true,
    promotionDiscount: 50,
    size: 'GRANDE',
    imageUrl:
        'https://ae01.alicdn.com/kf/H5927ea2a7c074984a8f9d9601d3e00e0t/Bata-de-ba-o-rosa-para-hombre-y-mujer-ropa-de-dormir-Sexy-secci-n-delgada.jpg_Q90.jpg_.webp',
  ),
];
