// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMDDHkRHcjIOn77OA6dLy-3frhPXfjKQ4',
    appId: '1:873436355955:web:739cfd50f3b4fbb4ff7906',
    messagingSenderId: '873436355955',
    projectId: 'pwa-sales2go',
    authDomain: 'pwa-sales2go.firebaseapp.com',
    databaseURL: 'https://pwa-sales2go.firebaseio.com',
    storageBucket: 'pwa-sales2go.appspot.com',
    measurementId: 'G-TLQLVFN176',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRzqyy0CAAK63aRdu0SyNlawZBdWZyMZ8',
    appId: '1:873436355955:android:4e545580e4d1c220ff7906',
    messagingSenderId: '873436355955',
    projectId: 'pwa-sales2go',
    databaseURL: 'https://pwa-sales2go.firebaseio.com',
    storageBucket: 'pwa-sales2go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWF5JUDJf9ruOAS5yknb3yGQpqCqo2QHY',
    appId: '1:873436355955:ios:fc925adc83e9363cff7906',
    messagingSenderId: '873436355955',
    projectId: 'pwa-sales2go',
    databaseURL: 'https://pwa-sales2go.firebaseio.com',
    storageBucket: 'pwa-sales2go.appspot.com',
    iosClientId: '873436355955-c6tdvqa9c4ifibbegk1f71l6univ53vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pwaSales2goFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWF5JUDJf9ruOAS5yknb3yGQpqCqo2QHY',
    appId: '1:873436355955:ios:fc925adc83e9363cff7906',
    messagingSenderId: '873436355955',
    projectId: 'pwa-sales2go',
    databaseURL: 'https://pwa-sales2go.firebaseio.com',
    storageBucket: 'pwa-sales2go.appspot.com',
    iosClientId: '873436355955-c6tdvqa9c4ifibbegk1f71l6univ53vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.pwaSales2goFlutter',
  );
}
