// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/models/shopping_cart_products.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2370540632508623834),
      name: 'ShoppingCartProduct',
      lastPropertyId: const IdUid(21, 3727172841384829065),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5100992528266329201),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(5, 7596685542364787523),
            name: 'code',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 7716031979793786700),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 3468392308484009496),
            name: 'promotion',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 8132879460390261999),
            name: 'productQuantity',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 7459871899526244167),
            name: 'productId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 5609711989173519954),
            name: 'listOfPricesId',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(18, 7658718255536929420),
            name: 'urlPicture',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(19, 3528385858162352867),
            name: 'totalAmount',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(20, 8910937102320734128),
            name: 'unitPrice',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(21, 3727172841384829065),
            name: 'availableStock',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2370540632508623834),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        944593588666398817,
        6127705484496877200,
        1097045211292602017,
        2860498095295675175,
        8880770054613509846,
        1670195316308917299,
        7866849489047978592,
        6305923191944941159,
        8856257174391709692,
        3295886441137857912
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ShoppingCartProduct: EntityDefinition<ShoppingCartProduct>(
        model: _entities[0],
        toOneRelations: (ShoppingCartProduct object) => [],
        toManyRelations: (ShoppingCartProduct object) => {},
        getId: (ShoppingCartProduct object) => object.id,
        setId: (ShoppingCartProduct object, int id) {
          object.id = id;
        },
        objectToFB: (ShoppingCartProduct object, fb.Builder fbb) {
          final codeOffset =
              object.code == null ? null : fbb.writeString(object.code!);
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final promotionOffset = object.promotion == null
              ? null
              : fbb.writeString(object.promotion!);
          final productIdOffset = object.productId == null
              ? null
              : fbb.writeString(object.productId!);
          final listOfPricesIdOffset = object.listOfPricesId == null
              ? null
              : fbb.writeString(object.listOfPricesId!);
          final urlPictureOffset = object.urlPicture == null
              ? null
              : fbb.writeString(object.urlPicture!);
          final totalAmountOffset = object.totalAmount == null
              ? null
              : fbb.writeString(object.totalAmount!);
          final unitPriceOffset = object.unitPrice == null
              ? null
              : fbb.writeString(object.unitPrice!);
          fbb.startTable(22);
          fbb.addInt64(0, object.id);
          fbb.addOffset(4, codeOffset);
          fbb.addOffset(8, nameOffset);
          fbb.addOffset(11, promotionOffset);
          fbb.addInt64(12, object.productQuantity);
          fbb.addOffset(13, productIdOffset);
          fbb.addOffset(14, listOfPricesIdOffset);
          fbb.addOffset(17, urlPictureOffset);
          fbb.addOffset(18, totalAmountOffset);
          fbb.addOffset(19, unitPriceOffset);
          fbb.addInt64(20, object.availableStock);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ShoppingCartProduct(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              productQuantity: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 28),
              availableStock: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 44),
              code: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 12),
              productId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 30),
              listOfPricesId: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 32),
              totalAmount: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 40),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20),
              promotion: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 26),
              unitPrice:
                  const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 42),
              urlPicture: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 38));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ShoppingCartProduct] entity fields to define ObjectBox queries.
class ShoppingCartProduct_ {
  /// see [ShoppingCartProduct.id]
  static final id =
      QueryIntegerProperty<ShoppingCartProduct>(_entities[0].properties[0]);

  /// see [ShoppingCartProduct.code]
  static final code =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[1]);

  /// see [ShoppingCartProduct.name]
  static final name =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[2]);

  /// see [ShoppingCartProduct.promotion]
  static final promotion =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[3]);

  /// see [ShoppingCartProduct.productQuantity]
  static final productQuantity =
      QueryIntegerProperty<ShoppingCartProduct>(_entities[0].properties[4]);

  /// see [ShoppingCartProduct.productId]
  static final productId =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[5]);

  /// see [ShoppingCartProduct.listOfPricesId]
  static final listOfPricesId =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[6]);

  /// see [ShoppingCartProduct.urlPicture]
  static final urlPicture =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[7]);

  /// see [ShoppingCartProduct.totalAmount]
  static final totalAmount =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[8]);

  /// see [ShoppingCartProduct.unitPrice]
  static final unitPrice =
      QueryStringProperty<ShoppingCartProduct>(_entities[0].properties[9]);

  /// see [ShoppingCartProduct.availableStock]
  static final availableStock =
      QueryIntegerProperty<ShoppingCartProduct>(_entities[0].properties[10]);
}
